---

- name: Update first master node
  when:
    - groups['kubernetes-master-nodes'][0] == inventory_hostname
  block:
    - name: Install these packages - kubeadm
      yum:
        name: "{{ rpm_list }}"
        state: present
        disable_excludes: kubernetes
      vars:
        rpm_list:
          - kubeadm-{{ VERSION }}.{{ MINOR_VERSION }}-0
      become: yes
    - name: Kubeadm upgrade plan
      command: >-
        {{ bin_dir }}/kubeadm upgrade plan
        #  delegate_to: "{{ groups['kubernetes-master-nodes'][0] }}"
      register: kubeadm_upgrade_plan
      changed_when: false
    
    - name: Print return information from the previous task kubeadm_upgrade_plan
      ansible.builtin.debug:
        var: kubeadm_upgrade_plan

    - name: Kubeadm upgrade apply 
      command: >-
        {{ bin_dir }}/kubeadm upgrade apply v1.22.11 --certificate-renewal=false --yes
      register: kubeadm_upgrade_plan
      changed_when: false
    - name: Install these packages - kubelet kubectl
      yum:
        name: "{{ rpm_list }}"
        state: present
        disable_excludes: kubernetes
      vars:
        rpm_list:
          - kubelet-{{ VERSION }}.{{ MINOR_VERSION }}-0
          - kubectl-{{ VERSION }}.{{ MINOR_VERSION }}-0
          - cri-o
      become: yes
    - name: restart service crio with demon_reload
      systemd:
        state: restarted
        enabled: yes
        daemon_reload: yes
        name: crio
    
    - name: restart service kubelet with demon_reload
      systemd:
        state: restarted
        enabled: yes
        daemon_reload: yes
        name: kubelet

